#' Check if sas.exe is in your PATH
#'
#' @returns Logical, TRUE if sas.exe is in your path, FALSE if not.
#' @noRd
SASinPATH <- function() {
  return(system2("where","sas.exe",stdout=FALSE,stderr=FALSE)==0)
}

#' Check if, and optionally change, names so that they adhere to SAS standards.
#'
#' @param x Character vector of names to be checked.
#' @param type Character, either "columns" or "dataset", referring to which type of SAS-names are targeted. In xpt version 5, column names may only be 8 characters long, otherwise 32.
#' @param repair Logical, whether to repair the names (change them to adhere to SAS standards) or to leave as is.
#' @param warn Logical, whether warning should be displayed when names have been repaired.
#' @param xpt_version Numeric, which version of xpt (SAS transport files) should be used (version 8 is default and recommended).
#'
#' @returns A character vector of names. If repair=FALSE then returns the original names, if repair=TRUE returns the repaired names.
#' @export
#'
#' @examples
#' # check if the names of an R data set are SAS compliant.
#' checkSASnames(iris)
#' # check and repair the names of an R data set.
#' iris2 <- checkSASnames(iris, repair=TRUE)
checkSASnames <- function(x, type="columns", repair=TRUE, warn=TRUE, xpt_version=8) {
  y <- x
  maxlength <- ifelse(type=="columns", ifelse(xpt_version==5,8L,32L), 32L)
  nonalphanum <- grepl("[^0-9a-zA-Z_]",x)
  #### better to use base::abbreviate first, then replace alphanumeric
  if (any(nonalphanum)) {
    if (repair) {
      y <- stringr::str_replace_all(x,"[^0-9a-zA-Z_]","_")
    } else {
      stop(sprintf("The following names have non-alpha-numeric characters which is not allowed in SAS: %s.",
            paste0(x[nonalphanum],collapse=", ")))
    }
  }
  toolong <- (nchar(y)>maxlength)
  if (any(toolong)) {
    if (repair) {
      y <- abbreviate(y,maxlength)
    } else {
      stop(sprintf("The following names are too long for SAS names: %s",
      paste0(x[toolong],collapse=", ")))
    }
  }
  chng <- (y!=x)
  if (any(chng)) {
    varchanges <- paste(x[chng],y[chng],sep=" --> ")
    if (warn) warning(sprintf("The following names were changed to comply with SAS standards:\n%s",paste0(varchanges,collapse="\n")))
  }
  return(y)
}




#' Execute SAS code from within R.
#'
#' A function which allows you to run SAS from within R (through batch-mode),
#' while using input data sets from R (argument `indata`).
#' Displays the SAS output in the R console and returns (a subset of, if optional argument `outdata` is used) the data sets produced in SAS and stored in the temporary "out"-library.
#'
#' SAS code is provided in the `sas_code` argument (preferably as a raw-string).
#' Input data sets from R will be placed in the SAS library "work" with names taken from the
#' named list supplied in `indata` (or simply "indata" if a single data set is supplied) and can be referenced in the `sas_code`.
#' Data sets produced in SAS that you want to output to R should be placed in the SAS library "out" (which is created by the function)
#' and should thus be written as out."name_of_data_set" in `sas_code`. If only a subset of the data sets in "out" should be returned, this can be specified in the `outdata` argument.
#'
#'
#' @param sas_code A raw string, or vector of raw strings, containing the SAS code to be executed.
#' @param indata A data set, or a named list of data sets, to be made available to SAS in the "work"-library. If a single data set is provided, it will be accessible under the name "indata". If a named list of datasets is provided, they will be available under their respective names in the named list.
#' @param outdata A character vector of the names of data sets you wish SASfromR to return. By default, `outdata=NULL`, all data sets placed in the "out"-library will be returned.
#' @param xpt_version Numeric. Which version of SAS transport files (xpt) do you wish to use (version 8 is default and recommended).
#' @param sas_path The full path to sas.exe (useful if it is not in your user PATH variable, though ideally you should add it to your PATH). Example: `sas_path=file.path("C:","Program Files","SASHome","SASFoundation","9.4","sas.exe")`.
#' @param output_file Path to where you wish to store the output (other than generated data sets) from your SAS call. By default the output will be displayed in the R console but not stored persistently. Output to console can be turned off using `display_output=FALSE`.
#' @param log_file Path to where you wish to store the log generated by SAS. By default the log will not be stored persistently. To view the log in console, choose `display_log=TRUE`.
#' @param display_log Logical, whether to display the SAS log in the R console.
#' @param display_output Logical, whether to display the SAS output in the R console.
#' @param remove_tempfiles Logical, whether to remove temporary files (e.g. SAS transport files, .sas7bdat-files, generated .sas-files, and log- or output-files unless they have been given more persistent paths through `output_file` and `log_file` arguments). Note: `remove_tempfiles=TRUE` is useful for debugging, but is not intended to be used on a regular basis. Temporary files are automatically removed when the current R-session ends.
#' @param repair_names Logical, whether to automatically repair the names of incoming data sets to adhere to SAS standards. If `FALSE` non-compliant names will throw an error.
#'
#' @returns A data set or named list of data sets, corresponding to those produced by SAS and placed in the "out"-library (unless otherwise specified in `outdata`. If no data sets are to be returned, SASfromR will return NULL (silently).
#' @export
#'
#' @examples
#' # Run PROC MEANS on existing SAS data set sashelp.cars, without output
#' # this will only return the output to console.
#' \dontrun{
#' SASfromR(r"(
#'   proc means data=sashelp.cars;
#'     class type;
#'     var mpg_highway;
#'   run;
#' )")
#' }
#'
#' # If an error occurs (which causes a non-zero exit), usually SASfromR will also output the SAS log.
#' # If you want to view the log anyway, you can do so with the option display_log = TRUE
#' \dontrun{
#' SASfromR(r"(
#'   proc means data=sashelp.cars;
#'     class type;
#'     var mpg_highway;
#'   run;
#' )", display_log=TRUE)
#' }
#'
#' # To make SASfromR return the results, output to out.means
#' \dontrun{
#' SASfromR(r"(
#'   proc means data=sashelp.cars;
#'     class type;
#'     var mpg_highway;
#'     ods output Summary = out.means;
#'   run;
#' )")
#' }
#'
#' # Run PROC MEANS on R data set mtcars by using indata argument.
#' # Note that when a single data set is supplied, it will obtain the name indata
#' # (or work.indata) in SAS.
#' \dontrun{
#' SASfromR(mtcars, r"(
#'   proc means data=indata;
#'     class vs;
#'     var mpg;
#'     ods output Summary = out.means;
#'   run;
#' )")
#' }
#'
#' # If you want to chose the name of the input data set in SAS, you
#' # can do so by wrapping it in a named list.
#' \dontrun{
#' SASfromR(list("mtcars"=mtcars), r"(
#'   proc means data=mtcars;
#'     class vs;
#'     var mpg;
#'     ods output Summary = out.means;
#'   run;
#' )")
#'}
#' # With named lists, you can make multiple R data sets available to SAS.
#' # Note that since the R data set iris contains names which are not SAS-compliant,
#' # these will be repaired and a warning will be issued telling you which names have
#' # been changed and what the new names are.
#' \dontrun{
#' SASfromR(list("mtcars"=mtcars, "iris"=iris), r"(
#'   proc means data=mtcars;
#'     class type;
#'     var mpg_highway;
#'     ods output Summary = out.mtcars_means;
#'   run;
#'   proc means data=iris;
#'     class Species;
#'     var Sepal_Length;
#'     ods output Summary = out.iris_means;
#'   run;
#' )")
#' }
SASfromR <- function(sas_code, indata=NULL, outdata=NULL,
  xpt_version = 8, sas_path = NULL,
  output_file=NULL, log_file=NULL,
  display_log=FALSE, display_output=TRUE,
  remove_tempfiles=TRUE, repair_names=TRUE) {


  # check to see if sas.exe is in path or if sas_path has been supplied.
  if (is.null(sas_path) & !SASinPATH()) stop("sas.exe does not appear to be in your PATH. Consider adding it to your PATH or supply the full path to sas.exe to the argument sas_path.")

  # create paths to indata and outdata directories in current temporary directory
  in_path <- tempfile(pattern="indata_")
  dir.create(in_path)
  out_path <- tempfile(pattern="outdata_")
  dir.create(out_path)
  # old...
  #in_path <- file.path(tempdir(),"indata")
  #if (!dir.exists(in_path)) dir.create(in_path)
  #out_path <- file.path(tempdir(),"outdata")
  #if (!dir.exists(out_path)) dir.create(out_path)
  #script_header <- sprintf('libname out "%s";',out_path)
  if (!is.null(indata)) {
    # check input type
    if (!inherits(indata,"list") & !inherits(indata,"data.frame")) stop("Only dataframes or named lists of dataframes allowed for argument indata")
    if (inherits(indata,"list") & is.null(names(indata))) stop("Only named lists are allowed for argument indata")
    # Handle case when only dataframe supplied
    if (inherits(indata,"data.frame")) {
      indata <- list("indata" = indata)
      message('Because no name was supplied for input datasets it will be named "indata". In SAS-code you can refer to it as "work.indata".')
    }
    ######-------------- move all this to export_R_data(indata,xpt_version,repair_names) [returns script_header]
    # check dataset names
    names(indata) <- checkSASnames(names(indata), type="dataset", xpt_version=xpt_version, repair=repair_names)
    # for each entry in indata
    for (in_name in names(indata)) {
      # check names of columns
      names(indata[[in_name]]) <- checkSASnames(names(indata[[in_name]]), type="columns", xpt_version=xpt_version, repair=repair_names)
      # create temporary files in indata temporary directory
      tmp <- file.path(in_path,sprintf("%s.xpt",in_name))
      # export to xpt
      haven::write_xpt(
        indata[[in_name]],
        path = tmp,
        version = xpt_version
      )
      # add import instructions to script header
      script_header <- c(
        script_header,
        sprintf('libname %s xport "%s";',in_name,tmp),
        ifelse(xpt_version==5,
          sprintf("data work.%s; set %s.%s; run;",in_name, in_name, in_name),
          sprintf("%%XPT2LOC(libref=work, filespec=%s);",in_name))
      )
    }
    ###### ---------
  }


  # add script_header to sas_script and save to temporary file
  sas_script <- tempfile(pattern="sas_script", fileext=".sas", tmpdir=in_path)
  readr::write_lines(c(script_header,sas_code),file=sas_script)

  # create output and log files if not specified
  if (is.null(output_file)) {
    sas_output <- tempfile(tmpdir=in_path)
  } else {
    sas_output <- output_file
  }
  if (is.null(log_file)) {
    sas_log <- tempfile(tmpdir=in_path)
  } else {
    sas_log <- log_file
  }
  #####------- move all this to execute_SAS(sas_script,sas_log,sas_output,sas_path)
  # produce command for script
  sas.exe <- ifelse(is.null(sas_path),"sas.exe",sas_path)
  return_code <- system2(sas.exe,
                         c("-nosplash", "-icon", "-sysin", sas_script,"-log", sas_log, "-print",sas_output),
                         stdout = FALSE,
                         stderr = FALSE
                         #stdout=file.path(getwd(),"system.out"),
                         #stderr=file.path(getwd(),"system.err")
  )

  # Handle errors (should be improved)
  if (return_code!="0") {
    if (return_code==2) {
      # if error, display log regardless, and
      cat("\n","\033[34mSAS log","\033[33m \n",
          paste0(readLines(sas_log),collapse="\n") |> stringr::str_replace_all("\f","\n"),
          "\033[0m\n")
      warning(sprintf("The exit-status was %s. Please check the SAS-log for errors.",return_code))
    } else if (return_code==127) {
      warning(sprintf("The exit-status was %s. This probably means that sas.exe is not in your PATH. Add the directory where sas.exe is located to your PATH or set it to working directory (not optimal).",return_code))
    } else {
      warning(sprintf("The exit-status was %s.",return_code))
    }
  }
  #####---------------

  # output sas log to console
  if (file.exists(sas_log) & display_log) {
    #####--------------- move all this to display_SAS_log(sas_log)
    cat("\n","\033[34mSAS log","\033[33m \n",
        paste0(readLines(sas_log),collapse="\n") |> stringr::str_replace_all("\f","\n"),
        "\033[0m\n")
    #####---------------
  }
  # output from sas to console
  if (file.exists(sas_output) & display_output) {
    #####--------------- move this to display_SAS_output(sas_output)
    cat("\n","\033[34mSAS output","\033[36m \n",
        paste0(readLines(sas_output),collapse="\n") |> stringr::str_replace_all("\f","\n"),
        "\033[0m\n")
    #####---------------
  }
  ######------- move all of this to import_SAS_data(out_path,out_data) in utils (returns outdata_list)
  # check the output directory for existing files and compare with listed outdata
  if (is.null(outdata)) {
    # if no outdata was supplied, load all .sas7bdat files in the output directory
    outdata_files <- list.files(out_path)
    outdata_files <- outdata_files[grepl(".*\\.sas7bdat",outdata_files)]
    outdata_paths <- file.path(out_path,outdata_files)
    names(outdata_paths) <- stringr::str_extract(outdata_files,"(.*)\\.sas7bdat", group=1)
  } else {
    # create paths to the output datasets and check that they exist
    outdata_paths <- file.path(out_path,paste0(outdata,".sas7bdat"))
    names(outdata_paths) <- outdata
    if (any(!file.exists(outdata_paths))) warning("One or more of the listed output datasets were not created. Check that you spelled it correctly and/or check the logs.")
    outdata_paths <- outdata_paths[file.exists(outdata_paths)]
  }

  # import all output datasets
  outdata_list <- list()
  if (length(outdata_paths)>0) {
    for (i in 1:length(outdata_paths)) {
      out_name <- names(outdata_paths)[i]
      out_file <- outdata_paths[i]
      outdata_list[[out_name]] <- haven::read_sas(out_file)
    }
  }
  #####-------

  # remove temporary files and directories
  on.exit({
    if (remove_tempfiles) {
      unlink(in_path, recursive=TRUE)
      unlink(out_path, recursive=TRUE)
    }
  })
  # return output data
  if (length(outdata_list)==0) {
    return(invisible(NULL))
  } else if (length(outdata_list)==1) {
    return(outdata_list[[1]])
  } else {
    return(outdata_list)
  }
}

#' Wrapper around SASfromR() to make input data set the first argument.
#'
#' In `SASfromR()`, `sas_code` is the first argument as it's primary purpose
#' is to execute SAS code (whether you want to attach R data sets or not).
#' However, in many cases, it is more natural to have the input data set(s) as
#' a first argument. This wrapper also makes it more easily usable in pipes.
#'
#' @param x R data set, or named list of data sets to be used in SAS.
#' @param sas_code A raw string (or vector of raw strings) containing SAS code to be executed.
#' @param ... Arguments passed on to `SASfromR()`.
#'
#' @seealso [SASfromR()]
#'
#' @returns A data set or named list of data sets, corresponding to those produced by SAS and placed in the "out"-library (unless otherwise specified in `outdata`. If no data sets are to be returned, SASfromR will return NULL (silently).
#' @export
#'
#' @examples
#' # Run PROC MEANS on the mtcars data set and return results.
#' # Note: When a single data set is supplied it will obtain the name indata in SAS.
#' \dontrun{
#' withSAS(mtcars, r"(
#'   proc means data=indata;
#'     class vs;
#'     var mpg;
#'     ods output Summary = out.means;
#'   run;
#' )")
#' }
#'
#' # Example utilizing withSAS() in a pipe
#' \dontrun{
#' mtcars |>
#'   dplyr::filter(am==0) |>
#'   withSAS(r"(
#'    proc means data=indata;
#'      class vs;
#'      var mpg;
#'      ods output Summary = out.means;
#'    run;
#'  )") |>
#'  flextable::flextable()
#'  }
withSAS <- function(x=NULL, sas_code, ...) {
  SASfromR(sas_code=sas_code, indata=x, ...)
}

