#' Execute SAS code from within R.
#'
#' A function which allows you to run SAS from within R (through batch-mode),
#' while using input data sets from R (argument `indata`).
#' Displays the SAS output in the R console and returns (a subset of, if optional argument `outdata` is used) the data sets produced in SAS and stored in the temporary "out"-library.
#'
#' SAS code is provided in the `sas_code` argument (preferably as a raw-string).
#' Input data sets from R will be placed in the SAS library "work" with names taken from the
#' named list supplied in `indata` (or simply "indata" if a single data set is supplied) and can be referenced in the `sas_code`.
#' Data sets produced in SAS that you want to output to R should be placed in the SAS library "out" (which is created by the function)
#' and should thus be written as out."name_of_data_set" in `sas_code`. If only a subset of the data sets in "out" should be returned, this can be specified in the `outdata` argument.
#'
#'
#' @param sas_code A raw string, or vector of raw strings, containing the SAS code to be executed.
#' @param indata A data set, or a named list of data sets, to be made available to SAS in the "work"-library. If a single data set is provided, it will be accessible under the name "indata". If a named list of datasets is provided, they will be available under their respective names in the named list.
#' @param outdata A character vector of the names of data sets you wish SASfromR to return. By default, `outdata=NULL`, all data sets placed in the "out"-library will be returned.
#' @param xpt_version Numeric. Which version of SAS transport files (xpt) do you wish to use (version 8 is default and recommended).
#' @param sas_path The full path to sas.exe (useful if it is not in your user PATH variable, though ideally you should add it to your PATH). Example: `sas_path=file.path("C:","Program Files","SASHome","SASFoundation","9.4","sas.exe")`.
#' @param base_dir The full path to a directory where temporary (if remove_tempfiles=TRUE) files are stored. Defaults to the R sessions temporary directory.
#' @param output_file Path to where you wish to store the output (other than generated data sets) from your SAS call. By default the output will be displayed in the R console but not stored persistently. Output to console can be turned off using `display_output=FALSE`.
#' @param log_file Path to where you wish to store the log generated by SAS. By default the log will not be stored persistently. To view the log in console, choose `display_log=TRUE`.
#' @param display_log Logical, whether to display the SAS log in the R console.
#' @param display_output Logical, whether to display the SAS output in the R console.
#' @param remove_tempfiles Logical, whether to remove temporary files (e.g. SAS transport files, .sas7bdat-files, generated .sas-files, and log- or output-files unless they have been given more persistent paths through `output_file` and `log_file` arguments). Note: `remove_tempfiles=TRUE` is useful for debugging, but is not intended to be used on a regular basis. Temporary files are automatically removed when the current R-session ends.
#' @param repair_names Logical, whether to automatically repair the names of incoming data sets to adhere to SAS standards. If `FALSE` non-compliant names will throw an error.
#'
#' @returns A data set or named list of data sets, corresponding to those produced by SAS and placed in the "out"-library (unless otherwise specified in `outdata`. If no data sets are to be returned, SASfromR will return NULL (silently).
#' @export
#'
#' @examples
#' # Run PROC MEANS on existing SAS data set sashelp.cars, without output
#' # this will only return the output to console.
#' \dontrun{
#' SASfromR(r"(
#'   proc means data=sashelp.cars;
#'     class type;
#'     var mpg_highway;
#'   run;
#' )")
#' }
#'
#' # If an error occurs (which causes a non-zero exit), usually SASfromR will also output the SAS log.
#' # If you want to view the log anyway, you can do so with the option display_log = TRUE
#' \dontrun{
#' SASfromR(r"(
#'   proc means data=sashelp.cars;
#'     class type;
#'     var mpg_highway;
#'   run;
#' )", display_log=TRUE)
#' }
#'
#' # To make SASfromR return the results, output to out.means
#' \dontrun{
#' SASfromR(r"(
#'   proc means data=sashelp.cars;
#'     class type;
#'     var mpg_highway;
#'     ods output Summary = out.means;
#'   run;
#' )")
#' }
#'
#' # Run PROC MEANS on R data set mtcars by using indata argument.
#' # Note that when a single data set is supplied, it will obtain the name indata
#' # (or work.indata) in SAS.
#' \dontrun{
#' SASfromR(mtcars, r"(
#'   proc means data=indata;
#'     class vs;
#'     var mpg;
#'     ods output Summary = out.means;
#'   run;
#' )")
#' }
#'
#' # If you want to chose the name of the input data set in SAS, you
#' # can do so by wrapping it in a named list.
#' \dontrun{
#' SASfromR(list("mtcars"=mtcars), r"(
#'   proc means data=mtcars;
#'     class vs;
#'     var mpg;
#'     ods output Summary = out.means;
#'   run;
#' )")
#'}
#' # With named lists, you can make multiple R data sets available to SAS.
#' # Note that since the R data set iris contains names which are not SAS-compliant,
#' # these will be repaired and a warning will be issued telling you which names have
#' # been changed and what the new names are.
#' \dontrun{
#' SASfromR(list("mtcars"=mtcars, "iris"=iris), r"(
#'   proc means data=mtcars;
#'     class type;
#'     var mpg_highway;
#'     ods output Summary = out.mtcars_means;
#'   run;
#'   proc means data=iris;
#'     class Species;
#'     var Sepal_Length;
#'     ods output Summary = out.iris_means;
#'   run;
#' )")
#' }
SASfromR <- function(sas_code, indata=NULL, outdata=NULL,
  xpt_version = 8, sas_path = NULL, base_dir=tempdir(),
  output_file=NULL, log_file=NULL,
  display_log=FALSE, display_output=TRUE,
  remove_tempfiles=TRUE, repair_names=TRUE) {

  # create paths to indata and outdata directories in current temporary directory
  in_path <- tempfile(pattern="indata_", tmpdir=base_dir)
  dir.create(in_path)
  out_path <- tempfile(pattern="outdata_", tmpdir=base_dir)
  dir.create(out_path)
  out_path_fmt <- file.path(out_path,"fmt")
  dir.create(out_path_fmt)

  # create header that specifies the output path for SAS
  outdata_header <- stringr::str_glue('libname out "{out_path}"; libname fmt "{out_path_fmt}";')
  # create footer for format exports
  outdata_footer <- stringr::str_glue('proc format cntlout=fmt.fmt; run;')
  # export R data if it is supplied, create header for SAS to import
  indata_header <- export_R_data(indata,
                                 in_path = in_path,
                                 xpt_version  = xpt_version,
                                 warn = TRUE)

  # add script_headers to sas_script and save to temporary file
  sas_script <- tempfile(pattern="sas_script_", fileext=".sas", tmpdir=in_path)
  readr::write_lines(c(outdata_header, indata_header, sas_code, outdata_footer), file=sas_script)

  # create output and log files if not specified
  if (is.null(output_file)) {
    sas_output <- tempfile(tmpdir=in_path)
  } else {
    sas_output <- output_file
  }
  if (is.null(log_file)) {
    sas_log <- tempfile(tmpdir=in_path)
  } else {
    sas_log <- log_file
  }

  # execute SAS code
  execute_SAS_script(sas_script,
                     sas_path = sas_path,
                     sas_log = sas_log,
                     sas_output = sas_output,
                     display_output = display_output,
                     display_log = display_log)

  # remove temporary files and directories
  on.exit({
    if (remove_tempfiles) {
      unlink(in_path, recursive=TRUE)
      unlink(out_path, recursive=TRUE)
    }
  })

  # import all data from SAS
  return(import_SAS_data(out_path, outdata))

}

#' Wrapper around SASfromR() to make input data set the first argument.
#'
#' In `SASfromR()`, `sas_code` is the first argument as it's primary purpose
#' is to execute SAS code (whether you want to attach R data sets or not).
#' However, in many cases, it is more natural to have the input data set(s) as
#' a first argument. This wrapper also makes it more easily usable in pipes.
#'
#' @param x R data set, or named list of data sets to be used in SAS.
#' @param sas_code A raw string (or vector of raw strings) containing SAS code to be executed.
#' @param ... Arguments passed on to `SASfromR()`.
#'
#' @seealso [SASfromR()]
#'
#' @returns A data set or named list of data sets, corresponding to those produced by SAS and placed in the "out"-library (unless otherwise specified in `outdata`. If no data sets are to be returned, SASfromR will return NULL (silently).
#' @export
#'
#' @examples
#' # Run PROC MEANS on the mtcars data set and return results.
#' # Note: When a single data set is supplied it will obtain the name indata in SAS.
#' \dontrun{
#' withSAS(mtcars, r"(
#'   proc means data=indata;
#'     class vs;
#'     var mpg;
#'     ods output Summary = out.means;
#'   run;
#' )")
#' }
#'
#' # Example utilizing withSAS() in a pipe
#' \dontrun{
#' mtcars |>
#'   dplyr::filter(am==0) |>
#'   withSAS(r"(
#'    proc means data=indata;
#'      class vs;
#'      var mpg;
#'      ods output Summary = out.means;
#'    run;
#'  )") |>
#'  flextable::flextable()
#'  }
withSAS <- function(x=NULL, sas_code, ...) {
  SASfromR(sas_code=sas_code, indata=x, ...)
}

